[package]
name = "consumet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.2"
scraper = "0.19.0"
tokio = { version = "1.36.0", features = ["full"] }
url = "2.5.0"
