import { ISource, IVideo, VideoExtractor } from '../../models';
import { getSources } from './megacloud.getsrcs';
import CryptoJS from 'crypto-js';

class MegaCloud extends VideoExtractor {
  protected override serverName = 'MegaCloud';
  protected override sources: IVideo[] = [];

  async extract_old(embedIframeURL: URL, referer: string = 'https://hianime.to') {
    try {
      const extractedData: ISource = {
        subtitles: [],
        intro: {
          start: 0,
          end: 0,
        },
        outro: {
          start: 0,
          end: 0,
        },
        sources: [],
      };

      const resp = await getSources(embedIframeURL.href, referer);

      if (!resp) return extractedData;

      if (Array.isArray(resp.sources)) {
        extractedData.sources = resp.sources.map((s: { file: any; type: string }) => ({
          url: s.file,
          isM3U8: s.type === 'hls',
          type: s.type,
        }));
      }

      extractedData.intro = resp.intro ? resp.intro : extractedData.intro;
      extractedData.outro = resp.outro ? resp.outro : extractedData.outro;

      extractedData.subtitles = resp.tracks.map((track: { file: any; label: any; kind: any }) => ({
        url: track.file,
        lang: track.label ? track.label : track.kind,
      }));

      return {
        intro: extractedData.intro,
        outro: extractedData.outro,
        sources: extractedData.sources,
        subtitles: extractedData.subtitles,
      } satisfies ISource;
    } catch (err) {
      throw err;
    }
  }

  //credit to https://github.com/itzzzme/megacloud-keys for autogenerated keys
  async extract(embedIframeURL: URL, referer: string = 'https://hianime.to'): Promise<ISource> {
    try {
      const response = await fetch('https://api.lunaranime.ru/static/key.txt');
      const key = await response.text();
      const extractedData: ISource = {
        subtitles: [],
        intro: {
          start: 0,
          end: 0,
        },
        outro: {
          start: 0,
          end: 0,
        },
        sources: [],
      };

      const match = /\/([^\/\?]+)\?/.exec(embedIframeURL.href);

      const sourceId = match?.[1];

      if (!sourceId) throw new Error('Unable to extract sourceId from embed URL');

      const megacloudUrl = `https://megacloud.blog/embed-2/v2/e-1/getSources?id=${sourceId}`;
      const response2 = await fetch(megacloudUrl);
      const rawSourceData = await response2.json();

      console.log(rawSourceData);
      console.log(key);
      const encrypted = rawSourceData?.sources;
      if (!encrypted) throw new Error('Encrypted source missing in response');
      const decrypted = CryptoJS.AES.decrypt(encrypted, key).toString(CryptoJS.enc.Utf8);
      let decryptedSources;
      try {
        decryptedSources = JSON.parse(decrypted);
      } catch (e) {
        throw new Error('Decrypted data is not valid JSON');
      }

      extractedData.intro = rawSourceData.intro ? rawSourceData.intro : extractedData.intro;
      extractedData.outro = rawSourceData.outro ? rawSourceData.outro : extractedData.outro;

      extractedData.subtitles =
        rawSourceData.tracks?.map((track: any) => ({
          url: track.file,
          lang: track.label ? track.label : track.kind,
        })) || [];
      extractedData.sources = decryptedSources.map((s: any) => ({
        url: s.file,
        isM3U8: s.type === 'hls',
        type: s.type,
      }));

      return extractedData;
    } catch (err) {
      throw err;
    }
  }
}

export default MegaCloud;
